format project using black & isort
rNintendoSwitch/Parakarry pull request #12
Opened 2021-01-18 20:25 UTC by mralext20

# Pull request template
Use this template for all contributions made for the repository.

Please indicate all that apply with a checkmark. To make a check, convert brackets below to `[x]`.

* [ ] **Feature implementation**
* [ ] **Bug fix**
* [x] **Code change/improvement**
* [ ] **String change (i.e. grammar/spelling error or an addition)**

***

## Describe what your pull request does
uses black as a formatter / linter. also does automation via github actions.

## Related issues and extra details
Link to any issues that this PR is related to and include extra info such as pictures, if applicable.

2021-01-18 20:28 UTC, 7bitlyrus requested changes

2021-01-18 20:28 UTC, 7bitlyrus commented on .vscode/settings.json
> +{
Add to .gitignore and delete file

2021-01-18 20:28 UTC, 7bitlyrus commented on pyproject.toml
> +profile = "black"
add newline

2021-01-18 20:31 UTC, 7bitlyrus approved these changes

2021-01-19 00:13 UTC, MattBSG approved these changes

2021-01-19 00:13 UTC, merged